### ISSUE TITLE
Middleware won't catch errors in async routes  

### ISSUE THREAD

**Issue by NivGreenstein** [MapColonies/error-express-handler#11]
**Describe the bug**
I've created custom Errors that implement `HttpError` interface from `@map-colonies/error-express-handler`. 
For non-async routes, when error is being thrown, the middleware catches it and sends the right error and http code. 
For async routes, when the same error is thrown, the server crash. 
In order to solve this issue, I had to add Try-Catch for every async route. With this patch, I once again got the server to respond with the expected output (expected http code and message). 

**To Reproduce**
1. Create simple Express.JS server.
2. Create custom error as described in the screenshots. 
3.  Create routes as described in the screenshots.
4. register `getErrorHandlerMiddleware()` from `@map-colonies/error-express-handler`  as post routes middleware. Example: `app.use(getErrorHandlerMiddleware());` 

**Expected behavior**
I'd expect that the middleware will catch errors thrown at both async and non-async routes.

**Screenshots**
The custom error implementation: 
<img width="532" alt="Screenshot 2024-09-11 at 18 12 53" src="https://github.com/user-attachments/assets/7c4a7f97-d7ce-422a-82f1-1f9fcb413a3c">

Non-async route:
<img width="478" alt="Screenshot 2024-09-11 at 18 13 25" src="https://github.com/user-attachments/assets/062876a6-62b9-4d7e-b75d-2508a4857e61">

Postman response (as expected):
<img width="844" alt="Screenshot 2024-09-11 at 18 13 49" src="https://github.com/user-attachments/assets/5d5f1aa0-26d4-4162-91ac-e1fe0d1bc5f3">

Async route that throws the same error:
<img width="491" alt="Screenshot 2024-09-11 at 18 17 27" src="https://github.com/user-attachments/assets/76eb8e7a-9069-4f5f-81e8-deae11c3a9df">

 Error:
```
/<Path>/ts-server-boilerplate/src/serverBuilder.ts:72
        reject(new BadRequestError('temp route - bad request error'));
               ^


BadRequestError: temp route - bad request error
    at <anonymous> (/<Path>/ts-server-boilerplate/src/serverBuilder.ts:72:16)
    at new Promise (<anonymous>)
    at <anonymous> (/<Path>/ts-server-boilerplate/src/serverBuilder.ts:71:13)
    at <anonymous> (/<Path>/ts-server-boilerplate/node_modules/@opentelemetry/instrumentation-express/src/instrumentation.ts:223:27)
    at Layer.handle [as handle_request] (/<Path>/ts-server-boilerplate/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/<Path>/ts-server-boilerplate/node_modules/express/lib/router/index.js:328:13)
    at /<Path>/ts-server-boilerplate/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/<Path>/ts-server-boilerplate/node_modules/express/lib/router/index.js:346:12)
    at next (/<Path>/ts-server-boilerplate/node_modules/express/lib/router/index.js:280:10)
    at traceContexHeaderMiddleware (/<Path>/ts-server-boilerplate/node_modules/@map-colonies/telemetry/src/tracing/middleware/traceOnHeaderMiddleware.ts:16:12) {
  status: 400
}
```

Try-catch implementation:
<img width="520" alt="Screenshot 2024-09-11 at 18 19 57" src="https://github.com/user-attachments/assets/86e04f25-2384-4a2c-987d-bc54c826bf69">

**Comment by syncush** [comment]
@netanelC @shimoncohen are you aware of this bug ?

**Comment by syncush** [comment]
@NivGreenstein please use reject, resolve and next correctly.
You should
```js
return reject(new BadRequestError("message"));
```
same for resolve and next

**Comment by netanelC** [comment]
> @netanelC @shimoncohen are you aware of this bug ?

I wasn't aware, thanks
